### ISSUE TITLE
Composer Installation Fails - Could not Find Minimum Stable Version

### ISSUE THREAD

**Issue by ajith107** [ctasca/mage-bundle#1]
#### Description

- Just started to explore the extension. When trying to install the extension using the `composer require --dev ctasca/mage-bundle` command. The installation fails with the following error.

```
Could not find a version of package ctasca/mage-bundle matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability
```

It might be related to the release of a stable version.
Just adding it as part of the improvement, It would be great to have a stable version release.

#### Workarounds

- We can explicitly mention the version or the branch name to bypass the error and install the package.

```
composer require --dev ctasca/mage-bundle:v3.5.1-BETA
```

or 

```
composer require --dev ctasca/mage-bundle:dev-main
```

**Comment by ctasca** [comment]
@ajith107 Thank you. I'll add it to the README file as I still want to gather feedbacks before making a stable release.
