### ISSUE TITLE
Module Name is in the wrong format.

### ISSUE THREAD

**Issue by MintayRibkins** [ctasca/mage-bundle#7]
When I try to do this: 
./bin/magento magebundle:ui-component:create
I got an error:
 Enter Module Name (e.g. Company_Module):
 > Foo
Module Name is in the wrong format.
 Enter Module Name (e.g. Company_Module):
 > gooFoo
Module Name is in the wrong format.
 Enter Module Name (e.g. Company_Module):
 > Woofyroofy

In Validator.php line 199:
                                       
  Module Name is in the wrong format.  
                                       
magebundle:ui-component:create

**Comment by ctasca** [comment]
@MintayRibkins 

The format must be "Company_Module". for example Magento_Checkout. Foo, gooFoo,  Woofyroofy are not valid.

See screenshot...

![Screenshot 2023-10-26 at 10 25 51](https://github.com/ctasca/mage-bundle/assets/1621171/88d34c0b-87a9-42a0-9299-ebc48e3808ad)
